{"name": "test_add_category[test_006]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './images/image_1652590022.PNG'", "trace": "self = <selenium_lesson.web_base.lite_mall.mine_litemall_po.testcase_litemall.test_case_litemall.TestCaseLiteMall object at 0x00000271DAE71748>\ncategory_name = 'bobo'\n\n    @pytest.mark.parametrize('category_name',('a','b','c','lily','mary','bobo'),\n                             ids=['test_001','test_002','test_003','test_004','test_005','test_006']\n                             )\n    def test_add_category(self,category_name):\n>       res=LoginPage().login().click_category().add_category().create_category(category_name).get_category_result(category_name)\n\ntest_case_litemall.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\page_object\\categorypage.py:27: in get_category_result\n    self.get_screen()\n..\\page_object\\base.py:31: in get_screen\n    attachment_type=allure.attachment_type.PNG)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\allure_commons\\_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\manager.py:87: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\allure_pytest\\listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\allure_commons\\reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\manager.py:87: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\allure_commons\\logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\shutil.py:266: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = './images/image_1652590022.PNG'\ndst = 'E:\\\\py23\\\\selenium_lesson\\\\web_base\\\\lite_mall\\\\mine_litemall_po\\\\testcase_litemall\\\\report\\\\a2030201-6319-4910-8ed3-45003a764ecf-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        for fn in [src, dst]:\n            try:\n                st = os.stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n    \n        if not follow_symlinks and os.path.islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: './images/image_1652590022.PNG'\n\nc:\\users\\longmin\\appdata\\local\\programs\\python\\python37\\lib\\shutil.py:120: FileNotFoundError"}, "attachments": [{"name": "picture", "source": "a2030201-6319-4910-8ed3-45003a764ecf-attachment.png", "type": "image/png"}], "parameters": [{"name": "category_name", "value": "'bobo'"}], "start": 1652590018772, "stop": 1652590023160, "uuid": "bd56e976-fdbc-4d36-8543-b604de7c59d4", "historyId": "2870d22623bbc2b57e95208b05840858", "testCaseId": "b7281af36e7a3ba241db49a012ce5999", "fullName": "test_case_litemall.TestCaseLiteMall#test_add_category", "labels": [{"name": "suite", "value": "test_case_litemall"}, {"name": "subSuite", "value": "TestCaseLiteMall"}, {"name": "host", "value": "LAPTOP-6GSA86E7"}, {"name": "thread", "value": "11592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_litemall"}]}